07_Django_04_Templates/templproject/templapp/urls.py
from django.urls import path
from templapp import views

# SET UP TEMPLATE TAGGING!!
# django will automatically look for app_name
# tells django to look into templapp and find the urls that match
app_name = "templapp"

urlpatterns = [
    path("other", views.other, name="other"),
    path("relative", views.relative, name="relative"),
    path("base", views.base, name="base"),
    path("inheriting",views.inheriting, name="inheriting"),
    path("index_inheriting",views.index_inheriting, name="index_inheriting"),
    path("index_filter",views.index_filter, name="index_filter"),
]

07_Django_04_Templates/templproject/templproject/urls.py
from django.contrib import admin
from django.urls import path, include
from templapp import views 

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("templapp/", include("templapp.urls")),
]

07_Django_04_Templates/templproject/templapp/models.py
from django.db import models

# Create your models here.

07_Django_04_Templates/templproject/templapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "templapp/index.html")

def other(request):
    return render(request, "templapp/other.html")

def relative(request):
    return render(request, "templapp/relative_url_templates.html")

def base(request):
    # this is actually only a base template for the inheritance, but just to see it I created a view
    return render(request, "templapp/base.html")

def inheriting(request):
    return render(request, "templapp/inheriting_template.html")

def index_inheriting(request):
    return render(request,"templapp/index_inheriting.html")

def index_filter(request):
    context_dict = {"text":"Hello World","number":100}
    return render(request,"templapp/index_filter.html",context_dict)

07_Django_04_Templates/templproject/templates/templapp/base.html
<!DOCTYPE html>
<!--  this has to always be the first line -->

{% load static %}

<head>
    <meta charset="UTF-8">
    <!-- latest compiled and minified css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "templapp/css/base.css" %}>

    <!-- link to fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
        rel="stylesheet"
    />
    <title></title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'templapp:index_inheriting' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'templapp:other' %}">Other page</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        {% block body_block %}
        <!-- anything outside of this will be inherited if you extend -->
        {% endblock %}
    </div>

</body>

</html>

07_Django_04_Templates/templproject/templates/templapp/index.html
<!DOCTYPE html>

{% load static %}

<head>
    <meta charset="UTF-8">
    <!-- latest compiled and minified css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "templapp/css/index.css" %}>

    <!-- link to fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
        rel="stylesheet"
    />

    <title>INDEX</title>
</head>

<body>

    <div class="container-fluid">
        <h1>Example of index page or homepage</h1>
        <p>Go to /templapp/other or to /templapp/relative</p>
    </div>

</body>

</html>

07_Django_04_Templates/templproject/templates/templapp/index_filter.html
<!DOCTYPE html>

{% extends "templapp/base.html" %}

{% load custom_filters %}

{% block body_block %}
<!-- anything inside this is specific of this individual html -->
<h1>Page showing Django Template Filters</h1>
<br>
<h3>{{ text }}</h3>
<h3>{{ text | upper }}</h3>
<h3>{{ text | cut:'Hello' }}</h3>
<h3>{{ text | slice:3 }}</h3>
<br>
<h3>{{ number|add:"99" }}</h3>
{% endblock %}

07_Django_04_Templates/templproject/templates/templapp/index_inheriting.html
<!DOCTYPE html>

{% extends "templapp/base.html" %}

{% block body_block %}
<!-- anything inside this is specific of this individual html -->
<h1>Index Page with an example of template inheritance</h1>
<br>
<p>This is the index page with inheritance from the base.html template.</p>
<p><a href="{% url 'index' %}">Go to index</a> (homepage) to view the homepage (without inheritance)</p>
<p><a href="{% url 'templapp:other' %}">Go to /templapp/other</a></p>
<p><a href="{% url 'templapp:relative' %}">Go to /templapp/relative</a></p>
<p><a href="{% url 'templapp:base' %}">Go to /templapp/base</a> to view the base template from which other templates inherit from</p>
{% endblock %}

07_Django_04_Templates/templproject/templates/templapp/inheriting_template.html
<!DOCTYPE html>

{% extends "templapp/base.html" %}

{% block body_block %}
<!-- anything inside this is specific of this individual html -->
<h1>Page with an example of template inheritance</h1>
<h4>This is an example of template inheritance</h4>
{% endblock %}

07_Django_04_Templates/templproject/templates/templapp/other.html
<!DOCTYPE html>

{% load static %}

<head>
    <meta charset="UTF-8">
    <!-- latest compiled and minified css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "templapp/css/other.css" %}>

    <!-- link to fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
        rel="stylesheet"
    />

    <title>OTHER</title>
</head>

<body>

    <div class="container-fluid">
        <h1>Page "Other"</h1>
    </div>

</body>

</html>

07_Django_04_Templates/templproject/templates/templapp/relative_url_templates.html
<!DOCTYPE html>

{% load static %}

<head>
    <meta charset="UTF-8">
    <!-- latest compiled and minified css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "templapp/css/relative_url_templates.css" %}>

    <!-- link to fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
        rel="stylesheet"
    />

    <title>Relative URL Template</title>
</head>

<body>

    <div class="container-fluid">
        <h1>Relative URL Template Page</h1>
        <br>
        <br>
        <h2>Relative url (correct)</h2>
        <h5><a href="{% url 'templapp:other' %}">Other page - relative url</a></h5>
        <!-- app_name:name of url (as defined in urls.py) -->
        <br>
        <h2>To the admin page with relative url</h2>
        <h5><a href="{% url 'admin:index' %}">Admin page</a></h5>
        <br>
        <h2>To the index page with relative url</h2>
        <h5><a href="{% url 'index' %}">Index page</a></h5>
    </div>

</body>

</html>